site_name: rainui.dev
site_url: https://rainui.dev
# repo_url: https://github.com/rxinui/rainui.dev
repo_name: rxinui/rainui.dev
theme:
  name: simple-blog
  custom_dir: docs/overrides
  features:
    - navigation.indexes
    - navigation.path
    - navigation.tabs
nav:
  - index.md
  - blog/index.md
  - curriculum: cv.pdf
plugins:
  - search:
      enabled: true
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
extra:
  analytics:
    provider: custom
extra_css:
  - stylesheets/extra.css